services:
  ncache:
    build: .
    container_name: ncache
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: "200M"
    networks:
      - formstr

networks:
  formstr:
    external: true
