services:
  backend:
    build: .
    container_name: ncache
    ports:
      - "1421:${APPLICATION_PORT}"
    depends_on:
      - cache
    env_file:
      - .env
    restart: always

  cache:
    image: redis:6.2-alpine
    container_name: ncache-redis
    restart: always
    ports:
      - "8921:6379"
    env_file:
      - .env
